name: guess_num_test_task
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/play_button.png
    - assets/images/restart_button.png
    - assets/images/arrow_button.png
    - assets/images/arrow_icon.png

  fonts:
    - family: Public Pixel
      fonts:
        - asset: assets/fonts/PublicPixel-eZPz6.ttf
        

